### ISSUE TITLE
Name change?

### ISSUE THREAD

**Issue by djsegal** [FluxML/Tokamak#2]
Hey,

So I have a codebase that's designed to research tokamaks:

+ https://github.com/djsegal/Tokamak.jl

Is it possible to change the name of this project?

**Comment by djsegal** [comment]
this is the only place it's been mentioned in research so far:

+ http://meetings.aps.org/Meeting/DPP17/Session/BP11.108

**Comment by MikeInnes** [comment]
It's possible to change a package name, but unfortunately quite difficult for a new package to take the old name, so that's tricky.

I'd be open to suggestions for new names, if anyone has any.

**Comment by SimonDanisch** [comment]
https://en.wikipedia.org/wiki/Stellarator

**Comment by djsegal** [comment]
This doesn't really matter to me anymore, but I might be against using science terms because they sound cool?

Julias a language for computationalists and eventually a plasma physicist will want to use the following package names:

+ plasma(s)
+ fusion
+ tokamak
+ stellarator

Might be completely wrong though :(

**Comment by MikeInnes** [comment]
Pkg3 will bring namespaces in a few weeks, so it's not really a big deal – we can both have that name.
